apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-viewer
  namespace: spring-petclinic
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
